// <auto-generated />
using LasagnaWPF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LasagnaWPF.Migrations
{
    [DbContext(typeof(DatabaseLasagne))]
    [Migration("20190327153815_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("LasagnaWPF.Lasagna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<string>("Peso");

                    b.Property<double>("Prezzo");

                    b.Property<string>("UrlImmagine");

                    b.HasKey("Id");

                    b.ToTable("Lasagne");
                });
#pragma warning restore 612, 618
        }
    }
}
